spring.application.name=muslim-daily-companion
spring.datasource.url=jdbc:mysql://localhost:3306/muslim_daily_companion
spring.datasource.username=root
spring.datasource.password=Yasarmeera@24
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true